[package]
name = "rust_kvs"
version.workspace = true
edition.workspace = true

[dependencies]
adler32.workspace = true
tinyjson.workspace = true

[dev-dependencies]
tempfile = "3.20"

[features]
default = ["mock_backend"]
mock_backend = []
json_backend = []
