name: Component Integration Tests
on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]
jobs:
  component-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust build environment
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.83.0

      - name: Run tests
        run: cargo test --package rust_kvs --test cit_*
